# Common
alias ls="ls $LS_OPTIONS"
alias l="ls -l"
alias ll="ls -l"
alias la="ls -lA"
alias lh="ls -lh"
alias lah="ls -lAh"
alias vi="vim"
alias nano="nano -w"
alias mc="mc"
alias tm="tmux attach || tmux new"
alias yarn="yarn --no-emoji"
# Git
alias gc="git commit"
alias ga="git add"
alias gp="git push"
alias gu="git pull"
alias gf="git fetch"
alias gm="git merge"
